# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "/etc/prometheus/rules/*"
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9090']


  #- job_name: 'cadvisor'
  #  static_configs:
  #  - targets: ['192.168.50.137:18080']

  #- job_name: 'mysql'
  #  static_configs:
  #  - targets: ['192.168.50.137:19104']
  
  #- job_name: 'redis'
  #  static_configs:
  #  - targets: ['192.168.50.137:19121']

  #- job_name: 'nginx'
  #  static_configs:
  #  - targets: ['192.168.50.137:19113']

  #- job_name: 'mongodb'
  #  static_configs:
  #  - targets: ['192.168.50.137:19123']
  
  #- job_name: 'elasticsearch'
  #  static_configs:
  #  - targets: ['192.168.50.137:19114']  

  - job_name: 'node_exporter'
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    file_sd_configs:
    - refresh_interval: 5m
      files:
        - node_exporter/*.json
        - node_exporter/*.yml

  - job_name: 'elasticsearch_exporter'
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    file_sd_configs:
    - refresh_interval: 5m
      files:
        - elasticsearch_exporter/*.json
        - elasticsearch_exporter/*.yml

  - job_name: 'redis_exporter'
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    file_sd_configs:
    - refresh_interval: 5m
      files:
        - redis_exporter/*.json
        - redis_exporter/*.yml

  - job_name: 'postgres_exporter'
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    file_sd_configs:
    - refresh_interval: 5m
      files:
        - postgres_exporter/*.json
        - postgres_exporter/*.yml
