global:
  resolve_timeout: 5m
  wechat_api_url: 'https://qyapi.weixin.qq.com/cgi-bin/'
  wechat_api_corp_id: 'ww5fc93f267b956282'
  wechat_api_secret: 'V6laY3amvHEDn2js6BskFEkzZEK1i_nuuytDdM5uHAg'

templates:
  - '/etc/alertmanager/warn.tmpl'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 30m
  receiver: 'wechat'
receivers:
- name: 'wechat'
  wechat_configs:
  - send_resolved: true
    message: '{{ template "wechat.default.message" . }}'
    to_party: '35'
    agent_id: '1000020'
    api_secret: 'V6laY3amvHEDn2js6BskFEkzZEK1i_nuuytDdM5uHAg'
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance', 'job']
